name: CI Test
on:
  push:
    branches:
      - master
jobs:
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
        
    - uses: subosito/flutter-action@v1
      with:
          channel: 'stable'
          
    - run: flutter clean
    - run: flutter pub get
    
    #Create and Install Certificates
   # - run: echo ${{ secrets.P12 }}  | base64 --decode > CertificatesDecoded.p12
    #- run: security import CertificatesDecoded.p12 -P ${{ secrets.P12_PASSWORD }}
    
     #Create and install MobileProvision
    #- run: echo ${{ secrets.MOBILE_PROVISION }}  | base64 --decode > MobileProvision.mobileprovision
    #- run: mkdir  -p ~/Library/MobileDevice/Provisioning\ Profiles
    #- run: cp MobileProvision.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$(grep UUID -A1 -a MobileProvision.mobileprovision | grep -io "[-A-F0-9]\{36\}").mobileprovision
    
    - uses: sparkfabrik/ios-build-action@v1.1.0
      with:
        project-path: App.xcodeproj
        p12-base64: ${{ secrets.P12 }}
        certificate-password: ${{ secrets.P12_PASSWORD }}       
        mobileprovision-base64: ${{ secrets.MOBILEPROVISION_BASE64 }}
        code-signing-identity: 'Apple Distribution: Keamore Limited'
        team-id: ${{ secrets.TEAM_ID }}
        output-path: build/ios/archive

    #- run: flutter build ipa
    
    #- run: cd ios
    
    #Create IPA
   # - run: xcodebuild -exportArchive -archivePath ../build/ios/archive/Runner.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath ../build/ios/iosrelease.ipa -allowProvisioningUpdates
    
    - name: Upload iPA
      uses: actions/upload-artifact@master
      with:
        name: bliss_test.ipa
        path: build/ios/archive
        
  build_apk:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
          channel: 'dev'
    - run: flutter pub get
    - run: flutter build apk --debug
    - name: Upload APK
      uses: actions/upload-artifact@master
      with:
        name: app-debug.apk
        path: build/app/outputs/flutter-apk
        
  beta_ios:
    name: Upload iOS Beta to Firebase App Distribution
    needs: [build_ios]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: bliss_test.ipa
    - name: Upload IPA
      uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
      with:
        appId: ${{secrets.FIREBASE_IOS_APPID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        file: bliss_test.ipa
  beta_apk:
    name: Upload Android Beta to Firebase App Distribution
    needs: [build_apk]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: app-debug.apk
    - name: Upload APK
      uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
      with:
        appId: ${{secrets.FIREBASE_ANDROID_APPID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        file: app-debug.apk
