name: CI Test
on:
  push:
    branches:
      - master
jobs:
  build_ios:
    name: Build Flutter (iOS)
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
        
    - uses: subosito/flutter-action@v1
      with:
          channel: 'stable'
          
    - run: flutter clean
    - run: flutter pub get

    - uses: sparkfabrik/ios-build-action@v1.1.0
      with:
        project-path: ios/Runner.xcodeproj
        p12-base64: ${{ secrets.P12 }}
        #p12-key-base64: ${{ secrets.P12 }}
        #p12-cer-base64: ${{ secrets.P12 }}
        export-method: ad-hoc
        mobileprovision-base64: ${{ secrets.PROFILE }}
        code-signing-identity: ${{ secrets.CODE_SIGNING_IDENTITY }}
        team-id: ${{ secrets.TEAM_ID }}
        workspace-path: ios/Runner.xcworkspace
        output-path: build/ios/archive

    - name: Upload iPA
      uses: actions/upload-artifact@master
      with:
        name: bliss_test.ipa
        path: build/ios/archive
        
  build_apk:
    name: Build Flutter (Android)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
          channel: 'dev'
    - run: flutter pub get
    - run: flutter build apk --debug
    - name: Upload APK
      uses: actions/upload-artifact@master
      with:
        name: app-debug.apk
        path: build/app/outputs/flutter-apk
        
  beta_ios:
    name: Upload iOS Beta to Firebase App Distribution
    needs: [build_ios]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: bliss_test.ipa
    - name: Upload IPA
      uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
      with:
        appId: ${{secrets.FIREBASE_IOS_APPID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        file: bliss_test.ipa
  beta_apk:
    name: Upload Android Beta to Firebase App Distribution
    needs: [build_apk]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: app-debug.apk
    - name: Upload APK
      uses: wzieba/Firebase-Distribution-Github-Action@v1.3.2
      with:
        appId: ${{secrets.FIREBASE_ANDROID_APPID}}
        token: ${{secrets.FIREBASE_TOKEN}}
        groups: testers
        file: app-debug.apk
